spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: rootroot
    url: jdbc:mysql://localhost:3306/lieferpronto
  jpa:
    hibernate:
      ddl-auto: update
