spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: <username>
    password: <pwd>
    url: jdbc:mysql://localhost:3306/lieferpronto
    data: classpath:data.sql
    initialization-mode: always
    sql-script-encoding: utf-8
  jpa:
    hibernate:
      ddl-auto: create
